apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    # Use the GKE-specific class annotation
    kubernetes.io/ingress.class: "gce"
    # GKE Autopilot creates an external LB by default, 
    # but you can specify static IPs or managed certs here later.
spec:
  # Crucial: Change this from 'alb' to 'gce'
  ingressClassName: gce 
  rules:
    - http:
        paths:
          - path: /* # GKE logic: use /* for the root path
            pathType: ImplementationSpecific  # Standard for GKE Native Ingress
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: {{ .Values.service.port }}
